version: '2'

services:
  api:
    image: node:6.9.1
    user: '33'
    command: ["bash", "start.sh"]
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 4546:80
    environment:
      - PORT=80
      - DEBUG=true
