version: '2'

services:
  api:
    image: node:6.9.1
    command: ['bash', 'start.sh']
    working_dir: /usr/src/app
    volumes: 
      - ./:/usr/src/app
    depends_on:
      - mongo
    ports:
      - 4546:80
    environment:
      - USER_ID=${UID}
      - PORT=80
      - DEBUG=true

  mongo:
    image: mongo:3.3
    user: "${UID}"
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./mocks:/mocks
